baseURL = ""
languageCode = "en-us"
title = "AWS Lambda - Serverless"
theme = "ananke"

[params.lambdaComments]
endpoint = "https://opr8bewo79.execute-api.us-east-2.amazonaws.com/default/student1002-comments-post"